[kthxbye] Revert "Makefile: add additional GCC 8 related optimization flags"
Error: invalid operands (.text.unlikely and .text sections) for `-'

This reverts commit c175cd9296e3ebf362f17f216b1228a25c702d5c.