msm: camera: Remove unnecessary null check in msm_remove_session_cmd_ack_q
Clang warns:

../drivers/media/platform/msm/camera_v2/msm.c:614:18: error: address of
'cmd_ack->command_q' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
        if (!(&cmd_ack->command_q))
            ~  ~~~~~~~~~^~~~~~~~~
../drivers/media/platform/msm/camera_v2/msm.c:624:32: error: address of
'session->command_ack_q' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
        if ((!session) || !(&session->command_ack_q))
                          ~  ~~~~~~~~~^~~~~~~~~~~~~
2 errors generated.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit 168e58d03f1ac3d372d306fbda0c5ac9e59d4f87)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>