soc: qcom: spm: Remove pointless BUG_ON
Clang warns:

../drivers/soc/qcom/msm-spm.c:156:15: error: address of array
'dev->reg_shadow' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
        BUG_ON(!dev->reg_shadow);
               ~~~~~~^~~~~~~~~~

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit 62b76d861733627722e246ffca5133127b0a2073)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>