msm: jpegdma: Fix maybe-uninitialized warning
drivers/media/platform/msm/camera_v2/jpeg_dma/msm_jpeg_dma_hw.c: In function ‘msm_jpegdma_hw_calc_config’:
drivers/media/platform/msm/camera_v2/jpeg_dma/msm_jpeg_dma_hw.c:1006:26: error: ‘phase’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   plane->config[1].phase = phase;

Signed-off-by: celtare21 <celtare21@gmail.com>
(cherry picked from commit 255c219c4d76b92c82aad596c53401f1f26747a9)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>