msm: camera: Remove always false checks in msm_camera_{get,put}_clk_info
Clang warns:

../drivers/media/platform/msm/camera_v2/common/cam_soc_api.c:208:23:
error: address of 'pdev->dev' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
        if (!pdev || !&pdev->dev || !clk_info || !clk_ptr || !num_clk)
                     ~ ~~~~~~^~~

../drivers/media/platform/msm/camera_v2/common/cam_soc_api.c:510:23:
error: address of 'pdev->dev' will always evaluate to 'true'
[-Werror,-Wpointer-bool-conversion]
        if (!pdev || !&pdev->dev || !clk_info || !clk_ptr)
                     ~ ~~~~~~^~~

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit 25f98c1ebe245ba7e1ca67ff03871260973be1e2)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>