msm: sensor: flash: Remove unnecessary null checks in msm_flash_i2c_release
Clang warns:

../drivers/media/platform/msm/camera_v2/sensor/flash/msm_flash.c:366:21:
error: address of 'flash_ctrl->power_info' will always evaluate to
'true' [-Werror,-Wpointer-bool-conversion]
        if (!(&flash_ctrl->power_info) || !(&flash_ctrl->flash_i2c_client)) {
            ~  ~~~~~~~~~~~~^~~~~~~~~~
../drivers/media/platform/msm/camera_v2/sensor/flash/msm_flash.c:366:51:
error: address of 'flash_ctrl->flash_i2c_client' will always evaluate to
'true' [-Werror,-Wpointer-bool-conversion]
        if (!(&flash_ctrl->power_info) || !(&flash_ctrl->flash_i2c_client)) {
                                          ~ ~~~~~~~~~~~~^~~~~~~~~~~~~~~~
2 errors generated.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit fa004c9a8fc2456ed7a2556900cdc94130d42ffa)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>