wcd_cpe: fix buffer size
The latest Clang highlight this buffer size issue:

sound/soc/codecs/wcd_cpe_core.c:1981:2: error: 'snprintf' size argument
is too large; destination buffer has size 11, but size argument is 13
[-Werror,-Wfortify-source]
        snprintf(proc_name, (sizeof("cpe") + sizeof("_state") +

Fixed by adjusting the buffer size

Change-Id: Ica51297b39f89bec1a5e4aed4cd295e0bdd622d9
Signed-off-by: Jean-Baptiste Théou <jb@essential.com>
Signed-off-by: celtare21 <celtare21@gmail.com>
(cherry picked from commit 1e3540d13729892423912a988b7d6c2069c4c8b8)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>