bpf_dbg: do not initialise statics to 0
This patch fixes the checkpatch.pl error to bpf_dbg.c:

ERROR: do not initialise statics to 0

Signed-off-by: Wei Tang <tangwei@cmss.chinamobile.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 1490d2bd1bbcf9ad127f7764b7f28b26a55e011b)
Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>